CREATE DATABASE SALES_OPPORTUNITIES;

TRUNCATE sales_pipeline;

LOAD DATA INFILE '\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\sales_pipeline.csv'
INTO TABLE sales_pipeline
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM sales_pipeline;
SET SQL_SAFE_UPDATES =0;
UPDATE sales_pipeline
SET engage_date= str_to_date(engage_date, "%m/%d/%Y"); 

-- Total_sales
SELECT SUM(close_value) Total_sales FROM sales_pipeline;

-- SALES BY QUARTER & PRODUCT
SELECT  product_,EXTRACT(YEAR FROM close_date) YEAR,
EXTRACT(QUARTER FROM close_date) QUARTER,
SUM(close_value) Total_sales
 FROM sales_pipeline
 WHERE deal_stage = "Won"
 GROUP BY product_,YEAR,QUARTER;
 
 
 -- QUARTER SALES BY MANAGERS
 SELECT ST.manager, EXTRACT(YEAR FROM SP.close_date) Year,
 EXTRACT(QUARTER FROM SP.close_date) Quarter,
 SUM(SP.close_value) Total_sales FROM sales_pipeline SP
 JOIN sales_teams ST ON SP.sales_agent= ST.sales_agent
 WHERE SP.deal_stage = "Won"
 GROUP BY ST.manager,EXTRACT(YEAR FROM SP.close_date), 
 EXTRACT(QUARTER FROM SP.close_date)
 ORDER BY manager ASC;
 
 -- QAURTER SALES BY TOP 5 AGENTS
  SELECT ST.sales_agent, EXTRACT(YEAR FROM SP.close_date) Year,
 EXTRACT(QUARTER FROM SP.close_date) Quarter,
 SUM(SP.close_value) Total_sales FROM sales_pipeline SP
 JOIN sales_teams ST ON SP.sales_agent= ST.sales_agent
 WHERE SP.deal_stage = "Won"
 GROUP BY ST.sales_agent,EXTRACT(YEAR FROM SP.close_date), 
 EXTRACT(QUARTER FROM SP.close_date)
 ORDER BY Total_sales DESC
 LIMIT 5;
 
 SELECT ST.sales_agent,
 EXTRACT(YEAR FROM SP.close_date) Year,
 EXTRACT(QUARTER FROM SP.close_date) Quarter,
 SUM(SP.close_value) Total_sales FROM sales_pipeline SP
 JOIN sales_teams ST ON SP.sales_agent= ST.sales_agent
 WHERE SP.deal_stage = "Won"
 GROUP BY 1,2,3
 ORDER BY Total_sales DESC
 LIMIT 5;
 
 
 -- Total_sales by Product
 SELECT product_, SUM(close_value) Total_sales FROM sales_pipeline
 GROUP BY product_
 ORDER BY Total_sales DESC;
 
 -- TOP 10 SALES AGENT BY TOTAL_SALES
 
 SELECT sales_agent, SUM(close_value) Total_sales FROM sales_pipeline
 GROUP BY sales_agent
 ORDER BY Total_sales DESC
 LIMIT 10;

-- TOTAL SALES BY REGIONAL OFFICE
SELECT regional_office, SUM(close_value) Total_Sales
 FROM sales_pipeline SP
JOIN sales_teams ST 
ON SP.sales_agent=ST.sales_agent
GROUP BY regional_office
ORDER BY Total_Sales DESC;

-- TOTAL_SALES BY DEAL WON
SELECT  deal_stage,SUM(close_value) Total_SalesWon FROM sales_pipeline
WHERE deal_stage = "Won"
GROUP BY deal_stage;

-- TOTAL DEAL WON 
SELECT  deal_stage,COUNT(close_value) Total_DealWon FROM sales_pipeline
WHERE deal_stage = "Won"
GROUP BY deal_stage;

-- TOTAL DEAL LOST
SELECT  deal_stage,COUNT(close_value) Total_DealLost FROM sales_pipeline
WHERE deal_stage = "Lost"
GROUP BY deal_stage;


-- TOTAL DEAL STILL ENGAGING 
SELECT  deal_stage,COUNT(close_value) Total_DealStillEngaging FROM sales_pipeline
WHERE deal_stage = "Engaging"
GROUP BY deal_stage;

-- TOP 10 SALES_AGENT BY DEAL_WON & CLOSE VALUE
SELECT sales_agent,deal_stage, COUNT( deal_stage) Close_value
 FROM sales_pipeline
 WHERE deal_stage = "Won"
GROUP  BY sales_agent, deal_stage
ORDER BY Close_value DESC
LIMIT 10;

-- TOP 10 SALES_AGENT BY THEIR DEAL LOST AND CLOSE_VALUES
SELECT sales_agent,deal_stage, COUNT( deal_stage) Close_value
 FROM sales_pipeline
 WHERE deal_stage = "Lost"
GROUP  BY sales_agent, deal_stage
ORDER BY Close_value DESC
LIMIT 10;

-- TOP 10 SALES AGENTS BY DEAL ENGAGING AND CLOSE VALUES
SELECT sales_agent,deal_stage, COUNT( deal_stage) Close_value
 FROM sales_pipeline
 WHERE deal_stage = "Engaging"
GROUP  BY sales_agent, deal_stage
ORDER BY Close_value DESC
LIMIT 10;

-- DEAL EXECUTION BY NUMBER OF MONTHS
SELECT deal_stage, engage_date,close_date,MONTH(engage_date)-MONTH(close_date) 
AS MONTH_INTERVALS FROM sales_pipeline
ORDER BY MONTH_INTERVALS DESC;

-- TOTAL REVENUE
SELECT SUM(revenue) Total_revenue FROM accounts;


-- TOTAL REVENUE GENERATED BY EACH SECTOR
SELECT sector,SUM(revenue) Total_revenue FROM accounts
GROUP BY revenue,sector;

-- TOTAL REVENUE BY TECHNOLOGY SECTOR
SELECT sector,SUM(revenue) Total_revenue FROM accounts
WHERE sector = "technolgy"
GROUP BY revenue,sector;

-- TOTAL REVENUE BY accounts/company
SELECT account, SUM(revenue) Total_revenue FROM accounts
GROUP BY account, revenue
ORDER BY Total_revenue DESC;

-- Total_revenue by office location
SELECT office_location, SUM(revenue) Total_revenue From accounts
GROUP BY office_location, revenue
ORDER BY Total_revenue DESC;